apiVersion: v1
kind: ConfigMap
metadata:
  name: takahe
  labels:
    app: takahe
data:
  TAKAHE_DEBUG: "false"
  TAKAHE_DATABASE_SERVER: "postgres://takahe:secret@postgres/takahe"
  TAKAHE_SECRET_KEY: "insecure_secret_key"
  TAKAHE_MEDIA_BACKEND: "local:///takahe/media"
  TAKAHE_MAIN_DOMAIN: "example.com"
  TAKAHE_EMAIL_SERVER: "smtp://user:password@email-smtp.us-east-2.amazonaws.com:25/?tls=true"
  TAKAHE_EMAIL_FROM: "no-reply@example.com"
  TAKAHE_AUTO_ADMIN_EMAIL: "admin@example.com"
  TAKAHE_USE_PROXY_HEADERS: "true"
  TAKAHE_SENTRY_DSN: ""
  TAKAHE_ENVIRONMENT: "production"
